<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8" />
    <title>三次元日誌</title>

    

  <script src="https://ousttrue.github.io/plugins/elasticlunr.min.js" defer></script>
  <script src="https://ousttrue.github.io/search_index.en.js" defer></script>
  <script src="https://ousttrue.github.io/js/search.js" defer></script>

    

     
    <link rel="stylesheet" href="https://ousttrue.github.io/main.css">
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.min.css"
      />
    
  </head>

  <body class="container">
    <a class="site_title" href="https:&#x2F;&#x2F;ousttrue.github.io&#x2F;">
      <div>三次元日誌</div>
    </a>

    <nav class="nav">
      <a class="item" href="/tags/">tags</a>
      <a class="item" href="https://github.com/ousttrue" aria-label="github">
        <i class="fab fa-github fa-lg"></i>
      </a>
      

        
            <form class="navbar-form">
                <input id="userinput" class="form-control is-search" type="search" placeholder="Search docs..."
                    aria-label="Search docs..." autocomplete="off">
                <div id="suggestions" class="shadow bg-white rounded"></div>
            </form>
        
    </nav>

    <main class="main">
<div class="page">
<div class="content">
  <div class="headline">
  
  

  
  <a class="headline_title" href="https:&#x2F;&#x2F;ousttrue.github.io&#x2F;posts&#x2F;2015&#x2F;12&#x2F;21&#x2F;node-self-build&#x2F;"> node.js(Windows版)を自前ビルドする 
  

  
  </a>

  

  <div>
    <ul class="tags">
      <li class="headline_date">
        <div class="year">2015</div>
        <div class="md">1221</div>
      </li>
      
      

    </ul>
  </div>
</div>
 <p>謎のクラッシュ(FFIでネイティブプラグインがアクセス違反で死ぬ)を追跡するため、
VCのデバッガをアタッチするべく自前ビルドする。
node-v5.3.0.tar.xz</p>
<p>7zipで解凍。
python2系にpathを通してvcbuild.batをたたく。</p>
<blockquote>
<p>vcbuild.bat</p>
</blockquote>
<p>v8もlibuvも全部入りらしくあっさりとほぼビルドできた。
SignTool Error: No certificates were found that met all the given criteria.
Failed to sign exe</p>
<p>document
https://github.com/nodejs/node-v0.x-archive/wiki/Installation#building-on-windows
debugビルドの作り方はこう。</p>
<blockquote>
<p>vcbuild.bat nosign debug</p>
</blockquote>
<p>nodeをデバッグ実行</p>
<p>node-v5.3.0にnode.slnができているのでこれをVisualStudio2015で開く。
nodeをスタートアッププロジェクトに指定
nodeの設定のdebugタブで、カレントディレクトリとコマンドライン引数を指定
f5</p>
<p>例外が再現した
void CallbackInfo::DispatchToV8(callback_info *info, void *retval, void **parameters, bool dispatched) {
Nan::HandleScope scope;</p>
<p>static const char* errorMessage = &quot;ffi fatal: callback has been garbage collected!&quot;;</p>
<p>if (info-&gt;function == NULL) {
// throw an error instead of segfaulting.
// see: https://github.com/rbranson/node-ffi/issues/72
if (dispatched) {
Local<Value> errorFunctionArgv[1];
errorFunctionArgv[0] = Nan::New<String>(errorMessage).ToLocalChecked();
info-&gt;errorFunction-&gt;Call(1, errorFunctionArgv);
}
else {
Nan::ThrowError(errorMessage);
}
} else {
// invoke the registered callback function
Local<Value> functionArgv[2];
functionArgv[0] = WrapPointer((char *)retval, info-&gt;resultSize);
functionArgv[1] = WrapPointer((char *)parameters, sizeof(char *) * info-&gt;argc);
Local<Value> e = info-&gt;function-&gt;Call(2, functionArgv); // &lt;-- ここ。functionがnullptrになってるよ!
if (!e-&gt;IsUndefined()) {
if (dispatched) {
Local<Value> errorFunctionArgv[1];
errorFunctionArgv[0] = e;
info-&gt;errorFunction-&gt;Call(1, errorFunctionArgv);
} else {
Nan::ThrowError(e);
}
}
}
}</p>
<p>ううむ。if文でnullチェックしてるのにelse側に落ちてるな。矢張りスレッドとかGCが絡んでいそうな気がするぞ。
ちょうどnode-ffiでjavascriptのコールバックを呼び出しているところなのではないか。
コールスタック</p>
<blockquote>
<p>ffi_bindings.node!CallbackInfo::DispatchToV8(_callback_info * info, void * retval, void * * parameters, bool dispatched) 行 73   C++
ffi_bindings.node!CallbackInfo::WatcherCallback(uv_async_s * w, int revents) 行 94   C++
node.exe!uv_process_async_wakeup_req(uv_loop_s * loop, uv_async_s * handle, uv_req_s * req) 行 97    C</p>
</blockquote>
<p>よく見るとまさにffi_bindings.node(node-ffiのネイティブプラグイン)内で問題が発生している。
呼び出しスレッドはメインスレッドか・・・。
何回も試してみると例外がむしろdllのスレッド側で起こることの方が多い。
他にWaitSingleObjectがstdcallの関数をスレッド実行しているものが４本。
ひょっとして、コールバックの頻度が高すぎなんじゃないのか・・・。
callback_infoはffiの構造体。こいつのデストラクタが呼ばれているのが確認できれば手がかりになるな。
で、callback_info-&gt;functionを解放する下記の部分がメインスレッドから呼ばれて、その後に
スレッドからのコールバック呼び出しがクラッシュしているらしいことを発見。
node_modules/ffi/src/callback_info.cc
/*</p>
<ul>
<li>Called when the <code>ffi_closure *</code> pointer (actually the &quot;code&quot; pointer) get's</li>
<li>GC'd on the JavaScript side. In this case we have to unwrap the</li>
<li><code>callback_info *</code> struct, dispose of the JS function Persistent reference,</li>
<li>then finally free the struct.
*/</li>
</ul>
<p>void closure_pointer_cb(char *data, void *hint) {
callback_info *info = reinterpret_cast&lt;callback_info *&gt;(hint);
// dispose of the Persistent function reference
delete info-&gt;function;
info-&gt;function = NULL;
// now we can free the closure data
ffi_closure_free(info);
}</p>
<p>コールスタック</p>
<blockquote>
<p>ffi_bindings.node!closure_pointer_cb(char * data, void * hint) 行 42 C++
node.exe!node::Buffer::CallbackInfo::WeakCallback(v8::Isolate * isolate, v8::Local<a href="v8::Object">v8::Object</a> object) 行 159    C++</p>
</blockquote>
<pre style="background-color:#2b303b;">
<code> 省略

node.exe!v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace space, const char * gc_reason, const v8::GCCallbackFlags callbackFlags) 行 556 C++

 省略

node.exe!node::Buffer::New(v8::Isolate * isolate, char * data, unsigned int length, void (char *, void *) * callback, void * hint) 行 347    C++
binding.node!`anonymous namespace'::WrapPointer(char * ptr, unsigned int length) 行 147  C++
binding.node!`anonymous namespace'::ReadPointer(const Nan::FunctionCallbackInfo&lt;v8::Value&gt; &amp; info) 行 261    C++
binding.node!Nan::imp::FunctionCallbackWrapper(const v8::FunctionCallbackInfo&lt;v8::Value&gt; &amp; info) 行 174  C++
</code></pre>
<p>なんか、GCが発動して回収されちゃっているぽい？
2015/09/20</p>
<ul>
<li>Nodejs GC is crashing when a C function is returning NULL
むしろこっちか
2015/11/05</li>
<li>Node.js v5.0.0でnode-ffiやNodObjCが動かない
しかし、うちのnode.jsは</li>
</ul>
<blockquote>
<p>node --version
v5.3.0</p>
</blockquote>
<p>うむ。
むしろこっちか
2015/09/15</p>
<ul>
<li>ffi.Function underlying Callback is garbage collected
死ななくなった。これっぽいな。
64bit版で試してみる
これはこれで死ぬ。
まとめ</li>
</ul>
<p>node-ffiのFunctionでGCに回収されてしまう書き方のところがある(FFI.Function内)
32bit版のnode-ffiではSTDCALLを指定できる(ABI=2)
64bit版のnode-ffiではIA64にされるのでSTDCALLは動かぬ</p>
<p>gypでのIA64とX64の扱いの違いがわかったら修正できるかな。
X86_WIN32の時にFFI_STDCALLを定義する修正をプルリクしてみよう。</p>

</div>

<nav class="toc">


</nav>
</div>
</main>

    <footer class="footer">Powered by <a href="https://www.getzola.org/">Zola</a> <a href="https://github.com/ousttrue/zola/tree/custom">custom</a></footer>

  </body>
</html>
